# -*- coding: utf-8 -*-
"""Load_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UYNuzL_pEGRkGc4Q5jiwUO22h5eWUFXA
"""

from huggingface_hub import hf_hub_download
import tensorflow as tf

# Download the model file from Hugging Face Hub
model_path = hf_hub_download(
    repo_id="Wahb12111/Deepfake_Image_Classification",
    filename="deepfake_image_classification_model.keras"
)

# Load the model
model = tf.keras.models.load_model(model_path)